[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "batch-on-kafka"
version = "0.1.0"

[project.scripts]
batch = "batch.cli:app"

[tool.ruff]
line-length = 100
