global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics

  - job_name: worker
    static_configs:
      - targets: ['worker:9090']
    metrics_path: /metrics
